import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ChevronDown, ChevronLeft, ChevronRight, Heart, Menu, Minus, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Truck, X } from 'lucide-react';
import './styles.css';

const company = { name:'LION FAST REACH LOGISTICS PTE. LTD', email:'LIONFASTREACH@outlook.com', address:'21 WOODLANDS CLOSE, #04-30, PRIMZ BIZHUB, SINGAPORE 737854' };
const imageSets = {
  furniture: '/products/furniture.webp', soft: '/products/soft.webp', daily: '/products/daily.webp', lighting: '/products/lighting.webp', utility: '/products/utility.webp'
};
const categories = [
  {id:'furniture', label:'Furniture', cn:'家具', note:'Structure for living'}, {id:'soft', label:'Soft Furnishings', cn:'软装', note:'Texture & tone'}, {id:'daily', label:'Home Essentials', cn:'家居日用品', note:'Everyday order'}, {id:'lighting', label:'Objects & Light', cn:'装饰摆件 & 灯饰', note:'Small atmospheres'}, {id:'utility', label:'Kitchen & Bath', cn:'餐厨 & 浴室用品', note:'Useful by design'}
];
const productNames = {
 furniture:['Arc Linen Sofa','Tide Oak Bed','Quietline Wardrobe','Gather Dining Table','Low Tide Coffee Table','Frame Media Console','Moss Drawer Chest','Nook Sideboard','Gridline Bookcase','Studio Writing Desk'],
  soft:['Cloudline Curtain','Morrow Wool Rug','Folded Form Cushion','Soft Focus Wall Art','Moss Floor Cushion','Sheer Day Curtain','Ribbed Blind','Tone-on-tone Wallcloth','Woven Horizon Tapestry','Loop Seat Cushion'],
 daily:['Field Cotton Bedding','Stack Fabric Box','Softstep Floor Mat','Cloudweight Quilt','Restwell Pillow','Linen Fitted Sheet','Daily Bath Towel','Wrap Bath Robe','Loop Laundry Basket','Pocket Storage Pouch'],
 lighting:['Dusk Scent Oil','Halo Table Lamp','Arc Floor Lamp','Line Wall Light','Roundhouse Clock','Softline Candle Holder','Form Study Sculpture','Glow Reading Light','Brass Task Lamp','Quiet Ember Diffuser'],
 utility:['Loom Placemat Set','Table Note Cloth','Heatfield Mat','Rail Kitchen Rack','Tide Shower Curtain','Surestep Bath Mat','Loop Towel Rail','Bathline Organizer','Pantry Caddy','Fold Dish Basket']
};
const priceMap = { furniture:[288,299,269,198,89,139,168,188,149,119], soft:[78,99,38,68,42,65,58,88,92,35], daily:[109,44,29,88,39,36,32,74,49,28], lighting:[24,89,179,109,49,39,79,66,82,34], utility:[22,45,29,58,52,34,46,62,39,27] };
const colorMap = { furniture:['#a87f69','#d2c1a9','#66766f','#ba8d67','#83776f','#a9b4a2','#4c5954','#bd9d7a','#798a93','#75645a'], soft:['#cfb7a4','#7d8a75','#8e736a','#bfaa8b','#78906f','#d9cdb6','#8b9a9b','#b9a58e','#8c7d71','#c9b4a2'], daily:['#d9d5c9','#879688','#c5a78e','#e2d4bc','#8aa0a0','#c8b7a4','#b1c2b8','#827c75','#a08b73','#b6a28f'], lighting:['#b0714f','#d2a160','#596665','#a77c62','#9d8d77','#c5a75f','#7f7770','#9aab9d','#b47b45','#d0b080'], utility:['#b29171','#d1b9a2','#8c9b83','#73827b','#c49b84','#a8b1a3','#b38d6e','#7f8a85','#b8956d','#9eaa9b'] };
const makeProducts = category => productNames[category].map((name,i)=>({ id:`${category}-${i}`, name, category, price:priceMap[category][i], image:`/products/${category}-${String(i+1).padStart(2,'0')}.webp`, color:colorMap[category][i], pos:'50% 50%', desc:`An original ${name.toLowerCase()} designed for quiet, useful living.` }));
const products = categories.flatMap(c=>makeProducts(c.id));

function ProductVisual({product, large=false}) { return <div className={`product-visual ${large?'large':''}`} style={{'--tone':product.color,'--pos':product.pos}}><img src={product.image} alt={product.name} /><span className="visual-wash" /><span className="product-mark">L</span></div> }
function Header({active,setActive,cartCount,onCart}) { return <header className="site-header"><a className="wordmark" href="#top" onClick={()=>setActive('all')}><span className="mark">L</span><span>LUMEHAUS</span></a><nav className="desktop-nav"><button onClick={()=>setActive('all')}>Shop</button>{categories.slice(0,4).map(c=><button key={c.id} className={active===c.id?'active':''} onClick={()=>setActive(c.id)}>{c.cn}</button>)}</nav><div className="header-actions"><button aria-label="Search"><Search size={19}/></button><button className="bag-button" onClick={onCart}><ShoppingBag size={19}/><span>{cartCount}</span></button><button className="mobile-menu"><Menu size={20}/></button></div></header> }
function Hero({setActive}) { return <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">The quiet edit · 2026</p><h1>把日子，<br/><em>安放得更好。</em></h1><p className="hero-text">LUMEHAUS 从生活的节奏出发，挑选耐看、耐用、耐相处的日常物件，让家有自己的呼吸。</p><button className="dark-button" onClick={()=>setActive('furniture')}>探索家具系列 <ArrowRight size={17}/></button></div><div className="hero-art"><div className="hero-image"><img src={imageSets.furniture} alt="LUMEHAUS furniture collection"/><div className="image-caption"><span>01 / 05</span><b>Quiet shapes<br/>for everyday life</b></div></div><div className="hero-stamp">L<br/><small>HOUSE<br/>OF<br/>OBJECTS</small></div></div></section> }
function CategoryStrip({setActive}) { return <section className="category-section"><div className="section-heading"><div><p className="eyebrow">Browse the collection</p><h2>按你的方式，<em>重新布置。</em></h2></div><button className="text-button" onClick={()=>setActive('all')}>View all <ArrowRight size={16}/></button></div><div className="category-grid">{categories.map((c,i)=><button className="category-card" key={c.id} onClick={()=>setActive(c.id)}><img src={imageSets[c.id]} alt={c.cn}/><span className="category-index">0{i+1}</span><span className="category-meta"><b>{c.label}</b><small>{c.note}</small></span><ArrowRight size={18}/></button>)}</div></section> }
function ProductCard({product,onAdd,onBuy}) { return <article className="product-card"><div className="card-image"><ProductVisual product={product}/><button className="heart" aria-label="Save"><Heart size={17}/></button><span className="product-category">{categories.find(c=>c.id===product.category)?.cn}</span></div><div className="product-info"><div><h3>{product.name}</h3><p>{product.desc}</p></div><strong>${product.price}</strong></div><div className="card-actions"><button onClick={()=>onAdd(product)}>Add to Cart</button><button onClick={()=>onBuy(product)}>Buy Now <span>· ${product.price}</span></button></div></article> }
function ProductGrid({active,onAdd,onBuy}) { const shown=active==='all'?products:products.filter(p=>p.category===active); return <section className="catalog"><div className="catalog-top"><div><p className="eyebrow">Selected objects</p><h2>{active==='all'?'Everything for a considered home':categories.find(c=>c.id===active)?.label}</h2></div><span>{shown.length} objects</span></div><div className="product-grid">{shown.map(p=><ProductCard key={p.id} product={p} onAdd={onAdd} onBuy={onBuy}/>)}</div></section> }
function TrustBand(){return <section className="trust-band"><div><Truck size={20}/><span><b>Thoughtful delivery</b><small>Clear dispatch updates, packed with care.</small></span></div><div><ShieldCheck size={20}/><span><b>30-day returns</b><small>Easy returns for unused pieces.</small></span></div><div><Sparkles size={20}/><span><b>Made to last</b><small>Materials picked for everyday living.</small></span></div></section>}
function CartDrawer({cart,onClose,onChange,onCheckout}) { const total=cart.reduce((s,i)=>s+i.price*i.qty,0); return <div className="drawer-backdrop" onClick={onClose}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">Your edit</p><h2>购物袋 <span>{cart.reduce((s,i)=>s+i.qty,0)}</span></h2></div><button onClick={onClose}><X/></button></div>{cart.length===0?<div className="empty-cart"><ShoppingBag size={32}/><p>你的购物袋还是空的。</p><button className="text-button" onClick={onClose}>继续浏览 <ArrowRight size={16}/></button></div>:<><div className="cart-items">{cart.map(item=><div className="cart-item" key={item.id}><ProductVisual product={item}/><div><h3>{item.name}</h3><b>${item.price}</b><div className="qty"><button onClick={()=>onChange(item,-1)}><Minus size={13}/></button><span>{item.qty}</span><button onClick={()=>onChange(item,1)}><Plus size={13}/></button></div></div></div>)}</div><div className="drawer-footer"><div><span>Subtotal</span><strong>${total}</strong></div><button className="dark-button full" onClick={onCheckout}>去结算 <ArrowRight size={17}/></button><small>含税费将在结算时计算</small></div></>}</aside></div> }
function Checkout({cart,onBack,onChange}) { const total=cart.reduce((s,i)=>s+i.price*i.qty,0); const [paid,setPaid]=useState(false); return <main className="checkout-page"><button className="back-link" onClick={onBack}><ChevronLeft size={17}/> 返回购物</button><div className="checkout-layout"><div className="checkout-main"><p className="eyebrow">Secure checkout</p><h1>完成你的订单。</h1>{paid?<div className="success-box"><div className="success-icon">✓</div><h2>订单已提交</h2><p>这是一个前端演示订单。真实支付通道需接入商户 PayPal / Visa 网关后生效。</p><button className="dark-button" onClick={onBack}>返回首页</button></div>:<><div className="checkout-form"><label>Email address<input type="email" defaultValue="" placeholder="you@example.com"/></label><div className="form-row"><label>First name<input placeholder="First name"/></label><label>Last name<input placeholder="Last name"/></label></div><label>Delivery address<input placeholder="Street and unit number"/></label><div className="form-row"><label>City<input placeholder="City"/></label><label>Postal code<input placeholder="Postal code"/></label></div><div className="payment-title"><span>Payment</span><div className="payment-icons"><span className="paypal">PayPal</span><span className="visa">VISA</span><span className="card-icon">▰</span></div></div><div className="payment-box"><label>Card number<input placeholder="1234  5678  9012  3456"/></label><div className="form-row"><label>Expiry date<input placeholder="MM / YY"/></label><label>Security code<input placeholder="CVC"/></label></div></div></div><button className="dark-button pay-button" onClick={()=>setPaid(true)}>Pay ${total} <ArrowRight size={17}/></button><p className="demo-note">安全支付演示 · PayPal / Visa / Credit Card</p></>}</div><div className="order-summary"><p className="eyebrow">Order summary</p>{cart.map(item=><div className="summary-item" key={item.id}><ProductVisual product={item}/><div><b>{item.name}</b><span>Qty {item.qty}</span></div><strong>${item.price*item.qty}</strong></div>)}<div className="summary-total"><span>Total</span><strong>${total}</strong></div></div></div></main> }
function Footer({setPage}) { const links=[['付款','payment'],['退货与退款','returns'],['取消政策','cancellation'],['关于我们','about'],['发货政策','shipping'],['订单追踪','tracking'],['服务条款','terms'],['隐私政策','privacy'],['DMCA','dmca']]; return <footer><div className="footer-main"><div className="footer-brand"><span className="mark">L</span><h2>Make room<br/><em>for living.</em></h2><p>为有质感的日常，挑选更好的物件。</p></div><div className="footer-columns"><div><b>Explore</b><button onClick={()=>setPage('shop')}>Shop all</button><button onClick={()=>setPage('shop')}>New arrivals</button><button onClick={()=>setPage('shop')}>Journal</button></div><div><b>Customer care</b>{links.slice(0,6).map(([label,id])=><button key={id} onClick={()=>setPage(id)}>{label}</button>)}</div><div><b>Legal</b>{links.slice(6).map(([label,id])=><button key={id} onClick={()=>setPage(id)}>{label}</button>)}</div></div></div><div className="footer-bottom"><span>© 2026 {company.name}</span><span>{company.address}</span><a href={`mailto:${company.email}`}>{company.email}</a></div></footer> }
function PolicyPage({page,onBack}) { const titles={payment:'Payment',returns:'Returns & Refunds',cancellation:'Cancellation Policy',about:'About LUMEHAUS',shipping:'Shipping Policy',tracking:'Order Tracking',terms:'Terms of Service',privacy:'Privacy Policy',dmca:'DMCA'}; const content={payment:'我们接受 PayPal、Visa 及主流信用卡。订单提交后，页面会跳转至安全支付流程。当前站点为前端演示，实际收款需配置对应商户账户。',returns:'未使用且保持原包装的商品可在签收后 30 天内申请退货。请先通过邮箱联系我们，获批后按指引寄回。定制、已使用或损坏商品不适用。',cancellation:'订单尚未进入发货流程前可申请取消。请发送订单号至官方邮箱，我们会确认取消状态。已发货订单按退货政策处理。',about:'LUMEHAUS 是一个关注日常尺度、材料触感与空间秩序的家居选物品牌。我们相信，好的家不需要喧闹，只需要更贴近你的生活。',shipping:'常规订单将在 2–5 个工作日内处理，配送时间视目的地而定。发货后会发送追踪信息。偏远地区或大件家具可能需要额外时间，我们会提前沟通。',tracking:'发货后，追踪编号会发送至下单邮箱。若 5 个工作日后仍未收到更新，请联系我们的客服邮箱查询。',privacy:'我们仅收集完成订单、配送、客服和站点运行所需的信息，不出售个人数据。支付信息由支付服务商处理，本站不保存完整银行卡号。',dmca:'如你认为本站内容侵犯了你的版权，请发送作品说明、权利证明、侵权链接与联系方式至官方邮箱，我们会在核实后处理。'}; const terms=['定义与范围','账户与信息','产品信息','价格与税费','下单与确认','支付授权','配送与签收','验货与异常','退货与退款','取消订单','知识产权','用户内容','禁止行为','免责声明','责任限制','条款变更','适用法律']; return <main className="policy-page"><button className="back-link" onClick={onBack}><ChevronLeft size={17}/> 返回首页</button><div className="policy-layout"><aside><p className="eyebrow">Customer care</p>{Object.entries(titles).map(([id,t])=><button className={page===id?'selected':''} onClick={()=>location.hash=id} key={id}>{t}<ChevronRight size={14}/></button>)}</aside><article><p className="eyebrow">LUMEHAUS / {page}</p><h1>{titles[page]}</h1>{page==='terms'?<>{terms.map((t,i)=><section className="policy-section" key={t}><h3>{i+1}. {t}</h3><p>本部分说明 LUMEHAUS 与客户之间关于{t}的基本约定。我们会以清晰、诚实和合理的方式提供服务，并在需要时通过订单邮箱与客户沟通。</p></section>)}</>:<><p className="policy-lead">{content[page]}</p><div className="policy-contact"><b>需要帮助？</b><p>请联系 {company.email}</p><p>{company.name}<br/>{company.address}</p></div></>}</article></div></main> }
function Admin(){return <main className="admin-page"><div className="admin-card"><span className="mark">L</span><p className="eyebrow">LUMEHAUS / Demo admin</p><h1>后台管理</h1><p>此处为前端演示后台，未连接真实数据库或身份认证。</p><div className="admin-stats"><div><b>50</b><span>Products</span></div><div><b>5</b><span>Categories</span></div><div><b>$0</b><span>Today</span></div></div><div className="demo-credentials"><span>演示账号</span><b>admin@lumehaus.demo</b><span>演示密码</span><b>Lumehaus2026!</b></div><button className="dark-button" onClick={()=>location.hash='shop'}>进入店铺 <ArrowRight size={17}/></button></div></main> }
function App(){ const [active,setActive]=useState('all'); const [cart,setCart]=useState([]); const [drawer,setDrawer]=useState(false); const [view,setView]=useState(location.hash.replace('#','')||'home'); const add=p=>{setCart(c=>{const found=c.find(i=>i.id===p.id);return found?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setDrawer(true)}; const buy=p=>{add(p);setView('checkout')}; const change=(p,d)=>setCart(c=>c.map(i=>i.id===p.id?{...i,qty:Math.max(0,i.qty+d)}:i).filter(i=>i.qty)); const go=p=>{setView(p); if(p==='shop')setActive('all'); window.scrollTo({top:0,behavior:'smooth'})}; const content=view==='checkout'?<Checkout cart={cart} onBack={()=>go('home')} onChange={change}/>:view==='admin'?<Admin/>:view==='home'?<><Header active={active} setActive={setActive} cartCount={cart.reduce((s,i)=>s+i.qty,0)} onCart={()=>setDrawer(true)}/><Hero setActive={setActive}/><CategoryStrip setActive={setActive}/><ProductGrid active={active} onAdd={add} onBuy={buy}/><TrustBand/><Footer setPage={go}/></>:view==='shop'?<><Header active={active} setActive={setActive} cartCount={cart.reduce((s,i)=>s+i.qty,0)} onCart={()=>setDrawer(true)}/><main className="shop-page"><div className="shop-intro"><p className="eyebrow">The full edit</p><h1>Objects that make<br/><em>space feel like yours.</em></h1><p>五个类目，五十件为日常而生的原创物件。</p></div><ProductGrid active={active} onAdd={add} onBuy={buy}/></main><Footer setPage={go}/></>:<><Header active={active} setActive={setActive} cartCount={cart.reduce((s,i)=>s+i.qty,0)} onCart={()=>setDrawer(true)}/><PolicyPage page={view} onBack={()=>go('home')}/><Footer setPage={go}/></>; return <><div onClick={e=>{const a=e.target.closest('a[href^="#"]'); if(a){e.preventDefault();go(a.getAttribute('href').slice(1))}}}>{content}</div>{drawer&&<CartDrawer cart={cart} onClose={()=>setDrawer(false)} onChange={change} onCheckout={()=>{setDrawer(false);go('checkout')}}/>}</> }
createRoot(document.getElementById('root')).render(<App/>);
